### ISSUE TITLE
Do you have the original lab files for other labs?

### ISSUE THREAD

**Issue by Pezhin** [andrewzigerelli/15-213#1]
On the website, I can only find the lab files for the first datalab.

Do you have the original files for the other labs?

P.S: Since 2015 Fall, they changed the textbook to the 3rd version so I wonder if the older labs files on github are out of date.

**Comment by andrewzigerelli** [comment]
Labs: http://csapp.cs.cmu.edu/3e/labs.html
The link to click is self-study handout.

It seems that they will be updating a few of the labs for the 3rd edition, but they are not released just yet.

**Comment by andrewzigerelli** [comment]
also
http://csapp.cs.cmu.edu/2e/proxylab-handout.tar
http://csapp.cs.cmu.edu/2e/shlab-handout.tar

**Comment by Pezhin** [comment]
thanks a lot
